# Generated by Django 5.1.6 on 2025-02-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_checklist_itemchecklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='data_criacao',
        ),
    ]
