# Generated by Django 5.1.6 on 2025-02-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_checklistitem_name'),
    ]

    operations = [
    ]
