# Generated by Django 5.1.6 on 2025-02-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formulario_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='name',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='descricao',
            field=models.CharField(default='Descrição Padrão', max_length=255),
        ),
    ]
