# Generated by Django 5.1.6 on 2025-02-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_formulario_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='name',
        ),
    ]
