# Generated by Django 5.1.6 on 2025-02-20 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_checklistitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
