# Generated by Django 5.1.6 on 2025-02-24 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_formulario_percentual_conclusao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Item do Checklist', 'verbose_name_plural': 'Itens do Checklist'},
        ),
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'Arquivo CSV', 'verbose_name_plural': 'Arquivos CSV'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='descricao',
            field=models.CharField(default='Descrição Padrão', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='csv/', verbose_name='Arquivo CSV'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='app.checklistitem', verbose_name='Itens do Checklist'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Formulário'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='percentual_conclusao',
            field=models.FloatField(default=0.0, verbose_name='Percentual de Conclusão'),
        ),
    ]
