# Generated by Django 5.1.6 on 2025-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_checklistitem_options_alter_csvfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nome',
        ),
        migrations.AddField(
            model_name='formulario',
            name='additional_comments',
            field=models.TextField(blank=True, default='N/A', null=True, verbose_name='Comentários Adicionais'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='assigned_to',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Atribuído a'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='assignment_group',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Grupo de Atribuição'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='channel',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='checks_and_handling',
            field=models.JSONField(default=list, verbose_name='Checks e Handling'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='country_of_request',
            field=models.CharField(default='N/A', max_length=100, verbose_name='País da Solicitação'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='created',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='format',
            field=models.JSONField(default=list, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='number',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='state',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='taxonomy',
            field=models.JSONField(default=list, verbose_name='Taxonomia'),
        ),
    ]
